/* 1. Who is working on projects for the customer Hotel Coral Exxex? */

SELECT EMPLOYEE.NAME, EMPLOYEE.TITLE
FROM EMPLOYEE, PROJECT, CUSTOMER, ASSINGED_TO
WHERE EMPLOYEE.ID = ASSINGED_TO.EMPLOYEE AND
 ASSINGED_TO.PROJECT = PROJECT.ID AND
 PROJECT.CUSTOMER = CUSTOMER.ID  AND
CUSTOMER.BUSINESS_NAME = 'Hotel Coral Essex';


/* 2. Paychecks need to be cut for salaried EMPLOYEEs for the month.  List NAMEs, ID's, AND check amounts for salaried EMPLOYEEs. */  

SELECT ID, NAME,  (PAY_RATE / 12)
FROM EMPLOYEE
WHERE PAY_CLASS = 'YR'
ORDER BY 3;


/* 3. What is the NAME of our latest hire? */

SELECT EMPLOYEE.NAME
FROM EMPLOYEE
WHERE EMPLOYEE.HIRE_DATE =
(SELECT  MAX(EMPLOYEE.HIRE_DATE)
FROM EMPLOYEE);


/* 4. Display the Cost AND COMPONENTs needed for a ENTRDMS SERVICE. */

SELECT COMPONENT.ID, COMPONENT.TYPE, COMPONENT.COST
FROM COMPONENT, MADE_OF, HARDWARE, SERVICE
WHERE  COMPONENT.ID = MADE_OF.COMPONENT AND 
MADE_OF.HARDWARE = HARDWARE.ID AND
SERVICE.HARDWARE = HARDWARE.ID AND 
SERVICE.CODE = 'ENTRDMS';


/* 5. A snow storm is about to Hit Denver, we need to call all of our Denver EMPLOYEEs.  What are thier NAMEs AND phone numbers? */

SELECT EMPLOYEE.NAME, EMPLOYEE.PHONE
FROM EMPLOYEE
WHERE EMPLOYEE.ADDRESS LIKE '%Denver%';


/* 6. What are the total earnings for employee D Isiah T. Billings-Clyde? */

SELECT EMPLOYEE.PAY_RATE * 
(SELECT SUM(HOURS_WORKED) FROM TIMESHEET WHERE TIMESHEET.EMPLOYEE = (SELECT EMPLOYEE.ID FROM EMPLOYEE WHERE EMPLOYEE.NAME = 'D Isiah T. Billings-Clyde')) 
FROM EMPLOYEE WHERE EMPLOYEE.NAME = 'D Isiah T. Billings-Clyde';


/* 7. How much has employee D Isiah T. Billings-Clyde earn for project 00308? */

SELECT EMPLOYEE.PAY_RATE * 
(SELECT SUM(HOURS_WORKED) FROM TIMESHEET WHERE TIMESHEET.PROJECT = 00308 AND TIMESHEET.EMPLOYEE = (SELECT EMPLOYEE.ID FROM EMPLOYEE WHERE EMPLOYEE.NAME = 'D Isiah T. Billings-Clyde')) 
FROM EMPLOYEE WHERE EMPLOYEE.NAME = 'D Isiah T. Billings-Clyde';


/* 8. How much has employee D Isiah T. Billings-Clyde earned working for Hotel Coral Essex? */

SELECT EMPLOYEE.PAY_RATE * 
(SELECT SUM(HOURS_WORKED) FROM TIMESHEET WHERE TIMESHEET.PROJECT IN 
(SELECT PROJECT.ID FROM PROJECT WHERE PROJECT.CUSTOMER = (SELECT CUSTOMER.ID FROM CUSTOMER WHERE CUSTOMER.BUSINESS_NAME = 'Hotel Coral Essex'))
AND TIMESHEET.EMPLOYEE = (SELECT EMPLOYEE.ID FROM EMPLOYEE WHERE EMPLOYEE.NAME = 'D Isiah T. Billings-Clyde')) 
FROM EMPLOYEE WHERE EMPLOYEE.NAME = 'D Isiah T. Billings-Clyde';

/* 9. How many hours were worked for all the projects with the business name Hotel Coral Essex? */

SELECT SUM(HOURS_WORKED) FROM TIMESHEET WHERE TIMESHEET.PROJECT IN 
(SELECT PROJECT.ID FROM PROJECT WHERE PROJECT.CUSTOMER = (SELECT CUSTOMER.ID FROM CUSTOMER WHERE CUSTOMER.BUSINESS_NAME = 'Hotel Coral Essex'));


/* 10. How much money has been paid out to employees who have worked for the customer Hotel Coral Essex? */

SELECT SUM(HOURS_WORKED * (SELECT EMP.PAY_RATE FROM EMPLOYEE AS EMP WHERE EMP.ID = EMPLOYEE)) FROM TIMESHEET WHERE TIMESHEET.PROJECT IN 
(SELECT PROJECT.ID FROM PROJECT WHERE PROJECT.CUSTOMER = (SELECT CUSTOMER.ID FROM CUSTOMER WHERE CUSTOMER.BUSINESS_NAME = 'Hotel Coral Essex'));